services:
  wordpress:
    #image: wordpress:6.4-php8.2-apache
    image: wordpress:6.4-php8.3-apache
    restart: always
    volumes:
      - ./_v/wp:/var/www/html
      - ./apps/${PROJECT_NAME}/theme:/var/www/html/wp-content/themes/${PROJECT_NAME}
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_DEBUG: 1

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./_v/db/data:/var/lib/mysql

  wpcli:
    image: wordpress:cli-php8.3
    user: 33:33
    command: tail -f /dev/null
    volumes:
      - ./_v/wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wp
      
